SELECT TOP (1000) [id]
      ,[username]
      ,[email]
      ,[password]
      ,[full_name]
      ,[role]
      ,[is_active]
      ,[created_at]
      ,[updated_at]
  FROM [phisingemail].[dbo].[users]