SELECT TOP (1000) [id]
      ,[user_id]
      ,[email_content]
      ,[sender_analysis]
      ,[content_analysis]
      ,[link_analysis]
      ,[risk_level]
      ,[threat_score]
      ,[recommendation]
      ,[analysis_date]
  FROM [phisingemail].[dbo].[email_analysis]